### ISSUE TITLE
Source of txt files of dataset

### ISSUE THREAD

**Issue by risingsun1412** [Carrotsniper/Multiclass-SGCN#1]
Hello! I'm working on trajectory visualization. I see that the content of the txt file in the dataset you are using is different from the official SDD data set. Where do these files come from? Because the frame id in the dataset you provided is inconsistent with the official one. I want to learn how the files are preprocessed.

**Comment by Carrotsniper** [comment]
Hi, thanks for your e-mail it is my pleasure to explain the SDD data we used for this paper.
Here is my screenshot for the original SDD dataset downloaded from the official website (Now the website is unavailable I think).

![image](https://github.com/Carrotsniper/Multiclass-SGCN/assets/36280292/64e359a2-8c51-4b52-9c77-c4cbfa051c7d)

As you can see, there are 10 columns in the table, each column is pre-defined by the dataset provider.
"
    1   Track ID. All rows with the same ID belong to the same path.
    2   xmin. The top left x-coordinate of the bounding box.
    3   ymin. The top left y-coordinate of the bounding box.
    4   xmax. The bottom right x-coordinate of the bounding box.
    5   ymax. The bottom right y-coordinate of the bounding box.
    6   frame. The frame that this annotation represents.
    7   lost. If 1, the annotation is outside of the view screen.
    8   occluded. If 1, the annotation is occluded.
    9   generated. If 1, the annotation was automatically interpolated.
    10  label. The label for this annotation, enclosed in quotation marks.
"

In our SDD version, we follow the work Semantic-STGCNN (https://arxiv.org/abs/2108.04740) to process the dataset that keeps
the Track ID, Frame ID, X, Y, Label [X = (xmin + xmax /2), Y the same ].

In most other research that using SDD for trajectory prediction as PCENet (ECCV 2020 https://arxiv.org/abs/2004.02025), YNet (ICCV 2021 https://arxiv.org/abs/2012.01526), you can find in their data processing file that they only keep the trajectories with label "**Pedestrian**", where we keep all the trajectories, so that this is the reason why we did not compare with many SOTA methods using SDD dataset.

Hope it helps.
